### PR TITLE
Invokable controllers

### PR DESCRIPTION
**Pull request by jakub-wolowski**
Here's my attempt on documenting the invokable controllers' generation.

On the way I spotted two small issues in the docs, pardon me for sending these in the same PR.

### CODE REVIEW

**Comment by jasonmccreary** [comment]
@jakub-wolowski, why is that sentence _obsolete_?

**Comment by jakub-wolowski** [comment]
@jasonmccreary sorry, maybe it's not the most precise word - but this sentence seems to be a copy from `render`, not applicable to `resource`

**Comment by jasonmccreary** [comment]
@jakub-wolowski thanks for the clarification. This was great!

**Comment by jakub-wolowski** [comment]
@jasonmccreary thanks, glad I could help

**Pull request merged**
